name: url_protocol_example
description: Demonstrates how to use the url_protocol plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_protocol:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
